# --- Database Configuration ---
DB_FILE = "market_data.db"

# --- Symbol Categories ---

# 1. MACRO_SYMBOLS: Market-wide indicators, dominance metrics, and equities.
MACRO_SYMBOLS = {
    "CRYPTOCAP:TOTAL": "TOTAL",
    "CRYPTOCAP:TOTAL2": "TOTAL2",
    "CRYPTOCAP:TOTAL3": "TOTAL3",
    "CRYPTOCAP:OTHERS": "OTHERS",
    "CRYPTOCAP:USDT.D": "USDT_D",
    "CRYPTOCAP:USDC.D": "USDC_D",
    "CRYPTOCAP:BTC.D": "BTC_D",
    "NASDAQ:NDX": "NDX",
    "BITSTAMP:BTCUSD": "BTCUSD",
    "BITSTAMP:ETHUSD": "ETHUSD",
}

# 2. ALL_SYMBOLS: A comprehensive list of all individual crypto assets for broad market analysis.
ALL_SYMBOLS = {
    # --- Previously Existing Symbols ---
    "BINANCE:BTCUSDT": "BTCUSDT", "BINANCE:ETHUSDT": "ETHUSDT", "BINANCE:XRPUSDT": "XRPUSDT", "BINANCE:BNBUSDT": "BNBUSDT",
    "BINANCE:SOLUSDT": "SOLUSDT", "BINANCE:DOGEUSDT": "DOGEUSDT", "BINANCE:TRXUSDT": "TRXUSDT", "BINANCE:ADAUSDT": "ADAUSDT",
    "CRYPTO:HYPEHUSD": "HYPEHUSD", "BINANCE:SUIUSDT": "SUIUSDT", "BINANCE:XLMUSDT": "XLMUSDT", "BINANCE:LINKUSDT": "LINKUSDT",
    "BINANCE:FILUSDT": "FILUSDT", "BINANCE:HBARUSDT": "HBARUSDT", "BINANCE:AVAXUSDT": "AVAXUSDT", "BINANCE:TONUSDT": "TONUSDT",
    "BINANCE:LTCUSDT": "LTCUSDT", "BINANCE:SHIBUSDT": "SHIBUSDT", "BINANCE:DOTUSDT": "DOTUSDT", "BINANCE:UNIUSDT": "UNIUSDT",
    "BINANCE:PEPEUSDT": "PEPEUSDT", "BINANCE:AAVEUSDT": "AAVEUSDT", "BINANCE:ENAUSDT": "ENAUSDT", "BINANCE:TAOUSDT": "TAOUSDT",
    "BINANCE:ATOMUSDT": "ATOMUSDT", "BINANCE:ETCUSDT": "ETCUSDT", "BINANCE:NEARUSDT": "NEARUSDT", "BINANCE:APTUSDT": "APTUSDT",
    "BINANCE:ONDOUSDT": "ONDOUSDT", "BINANCE:JUPUSDT": "JUPUSDT", "BINANCE:ICPUSDT": "ICPUSDT", "BYBIT:MNTUSDT": "MNTUSDT",
    "BINANCE:QNTUSDT": "QNTUSDT", "BINANCE:POLUSDT": "POLUSDT", "BINANCE:ALGOUSDT": "ALGOUSDT", "BINANCE:BONKUSDT": "BONKUSDT",
    "BINANCE:ARBUSDT": "ARBUSDT", "BINANCE:VETUSDT": "VETUSDT", "BINANCE:RENDERUSDT": "RENDERUSDT", "BINANCE:WLDUSDT": "WLDUSDT",
    "BINANCE:CRVUSDT": "CRVUSDT", "COINBASE:SEIUSD": "SEIUSD", "BITSTAMP:FLRUSD": "FLRUSD", "COINBASE:SKYUSD": "SKYUSD",
    "BINANCE:LDOUSDT": "LDOUSDT", "COINBASE:GRTUSD": "GRTUSD", "BINANCE:SANDUSDT": "SANDUSDT",
    "BINANCE:THETAUSDT": "THETAUSDT", "BINANCE:IOTAUSDT": "IOTAUSDT", "BINANCE:RAYUSDT": "RAYUSDT", "CRYPTO:GALAUSD": "GALAUSD",
    "BINANCE:PENDLEUSDT": "PENDLEUSDT", "BINANCE:BTTCUSDT": "BTTCUSDT", "COINBASE:MORPHOUSD": "MORPHOUSD", "BINANCE:JTOUSDT": "JTOUSDT",
    "BINANCE:SYRUPUSDT": "SYRUPUSDT", "BYBIT:HNTUSDT": "HNTUSDT", "COINBASE:PENGUUSD": "PENGUUSD", "COINBASE:TRUMPUSD": "TRUMPUSD",
    "BYBIT:SPXUSDT": "SPXUSDT", "CRYPTO:FLOKIUSD": "FLOKIUSD", "CRYPTO:FARTCOINUSD": "FARTCOINUSD", "BINANCE:WIFUSDT": "WIFUSDT",
    "BINANCE:RSRUSDT": "RSRUSDT", "OKX:CFGUSD": "CFGUSD", "BYBIT:PLUMEUSDT": "PLUMEUSDT", "BYBIT:XDCUSDT": "XDCUSDT", "BYBIT:ONDOUSDT": "ONDOUSDT_BYBIT",
    "COINBASE:EULUSD": "EULUSD", "BINANCE:INJUSDT": "INJUSDT", "COINBASE:AEROUSD": "AEROUSD", "OKX:MORPHOUSDT": "MORPHOUSDT_OKX", "COINBASE:BCHUSD": "BCHUSD",
    "OKX:CROUSDT": "CROUSDT", "BINANCE:FETUSDT": "FETUSDT", "BYBIT:IPUSDT": "IPUSDT", "BINANCE:FORMUSDT": "FORMUSDT", "BINANCE:STXUSDT": "STXUSDT", "BINANCE:TIAUSDT": "TIAUSDT",
    "BYBIT:PUMPUSDT": "PUMPUSDT", "BINANCE:IMXUSDT": "IMXUSDT", "BINANCE:ENSUSDT": "ENSUSDT", "BINANCE:CFXUSDT": "CFXUSDT", "BINANCE:CAKEUSDT": "CAKEUSDT", "BINANCE:SUSDT": "SUSDT",
    "BINANCE:VIRTUALUSDT": "VIRTUALUSDT", "BINANCE:AUSDT": "AUSDT", "MEXC:MUSDT": "MUSDT", "BINANCE:PYTHUSDT": "PYTHUSDT",
    "CRYPTO:BUSD": "BUSD", "BYBIT:BRETTUSDT": "BRETTUSDT", "BYBIT:MOGUSDT": "MOGUSDT", "CRYPTO:REKTCUSD": "REKTCUSD", "CRYPTO:SNEKUSD": "SNEKUSD",
    "OKX:TURBOUSDT": "TURBOUSDT", "COINBASE:TOSHIUSD": "TOSHIUSD", "BYBIT:POPCATUSDT": "POPCATUSDT",
    
    # --- NEWLY ADDED SYMBOLS ---
    "BINANCE:OPUSDT": "OPUSDT", "BINANCE:MKRUSDT": "MKRUSDT", "BINANCE:KAIAUSDT": "KAIAUSDT", "BINANCE:SUSDT": "SUSDT",
    "BINANCE:XTZUSDT": "XTZUSDT", "BINANCE:JASMYUSDT": "JASMYUSDT", "BINANCE:NEXOUSDT": "NEXOUSDT",
    "BINANCE:ETHFIUSDT": "ETHFIUSDT", "BINANCE:DEXEUSDT": "DEXEUSDT", "BINANCE:AXSUSDT": "AXSUSDT", "BINANCE:NEOUSDT": "NEOUSDT",
    "BINANCE:ZROUSDT": "ZROUSDT", "BINANCE:FLOWUSDT": "FLOWUSDT", "BINANCE:ZECUSDT": "ZECUSDT", "BINANCE:RUNEUSDT": "RUNEUSDT",
    "BINANCE:MANAUSDT": "MANAUSDT", "BINANCE:APEUSDT": "APEUSDT", "BINANCE:STRKUSDT": "STRKUSDT",
    "BINANCE:DYDXUSDT": "DYDXUSDT", "BINANCE:ARUSDT": "ARUSDT", "BINANCE:COMPUSDT": "COMPUSDT", "BINANCE:SUPERUSDT": "SUPERUSDT",
    "BINANCE:ZKUSDT": "ZKUSDT", "BINANCE:SUNUSDT": "SUNUSDT", "BINANCE:EGLDUSDT": "EGLDUSDT", "BINANCE:CVXUSDT": "CVXUSDT",
    "BINANCE:WUSDT": "WUSDT", "BINANCE:EIGENUSDT": "EIGENUSDT", "BINANCE:XECUSDT": "XECUSDT", "BINANCE:KAVAUSDT": "KAVAUSDT",
    "BINANCE:CHZUSDT": "CHZUSDT", "BINANCE:BEAMXUSDT": "BEAMXUSDT", "BINANCE:1INCHUSDT": "1INCHUSDT", "BINANCE:RONINUSDT": "RONINUSDT",
    "BINANCE:MOVEUSDT": "MOVEUSDT", "BINANCE:GNOUSDT": "GNOUSDT", "BINANCE:AXLUSDT": "AXLUSDT", "BINANCE:JSTUSDT": "JSTUSDT",
    "BINANCE:LUNCUSDT": "LUNCUSDT", "BINANCE:TWTUSDT": "TWTUSDT", "BINANCE:FTTUSDT": "FTTUSDT",
    "BINANCE:FXSUSDT": "FXSUSDT", "BINANCE:AMPUSDT": "AMPUSDT", "BINANCE:KMNOUSDT": "KMNOUSDT", "BINANCE:DCRUSDT": "DCRUSDT",
    "BINANCE:LPTUSDT": "LPTUSDT", "BINANCE:KAITOUSDT": "KAITOUSDT", "BINANCE:DASHUSDT": "DASHUSDT", "BINANCE:IOTXUSDT": "IOTXUSDT",
    "BINANCE:OMUSDT": "OMUSDT", "BINANCE:PROVEUSDT": "PROVEUSDT", "BINANCE:TFUELUSDT": "TFUELUSDT", "BINANCE:KSMUSDT": "KSMUSDT",
    "BINANCE:CKBUSDT": "CKBUSDT", "BINANCE:GLMUSDT": "GLMUSDT", "BINANCE:SFPUSDT": "SFPUSDT", "BINANCE:PNUTUSDT": "PNUTUSDT",
    "BINANCE:ROSEUSDT": "ROSEUSDT", "BINANCE:BERAUSDT": "BERAUSDT", "BINANCE:MINAUSDT": "MINAUSDT", "BINANCE:ARKMUSDT": "ARKMUSDT",
    "BINANCE:ZILUSDT": "ZILUSDT", "BINANCE:SUSHIUSDT": "SUSHIUSDT", "BINANCE:MEUSDT": "MEUSDT", "BINANCE:CELOUSDT": "CELOUSDT",
    "BINANCE:SNXUSDT": "SNXUSDT", "BINANCE:BATUSDT": "BATUSDT", "BINANCE:QTUMUSDT": "QTUMUSDT", "BINANCE:RVNUSDT": "RVNUSDT",
    "BINANCE:ZRXUSDT": "ZRXUSDT", "BINANCE:ASTRUSDT": "ASTRUSDT", "BINANCE:BIOUSDT": "BIOUSDT", "BINANCE:ACHUSDT": "ACHUSDT",
    "BINANCE:GASUSDT": "GASUSDT", "BINANCE:ORDIUSDT": "ORDIUSDT", "BINANCE:BLURUSDT": "BLURUSDT", "BINANCE:NOTUSDT": "NOTUSDT",
    "BINANCE:COWUSDT": "COWUSDT", "BINANCE:SAHARAUSDT": "SAHARAUSDT", "BINANCE:SAGAUSDT": "SAGAUSDT", "BINANCE:YFIUSDT": "YFIUSDT",
    "BINANCE:LUNAUSDT": "LUNAUSDT", "BINANCE:DYMUSDT": "DYMUSDT", "BINANCE:IDUSDT": "IDUSDT", "BINANCE:STGUSDT": "STGUSDT",
    "BINANCE:PROMUSDT": "PROMUSDT", "BINANCE:VANAUSDT": "VANAUSDT", "BINANCE:RPLUSDT": "RPLUSDT", "BINANCE:ALTUSDT": "ALTUSDT",
    "BINANCE:BIGTIMEUSDT": "BIGTIMEUSDT", "BINANCE:VTHOUSDT": "VTHOUSDT", "BINANCE:NEIROUSDT": "NEIROUSDT", "BINANCE:LAYERUSDT": "LAYERUSDT",
    "BINANCE:NXPCUSDT": "NXPCUSDT", "BINANCE:HOTUSDT": "HOTUSDT", "BINANCE:SCUSDT": "SCUSDT", "BINANCE:GMXUSDT": "GMXUSDT",
    "BINANCE:POWRUSDT": "POWRUSDT", "BINANCE:TUSDT": "TUSDT", "BINANCE:ACXUSDT": "ACXUSDT", "BINANCE:SPKUSDT": "SPKUSDT",
    "BINANCE:ONEUSDT": "ONEUSDT", "BINANCE:OMNIUSDT": "OMNIUSDT", "BINANCE:UMAUSDT": "UMAUSDT", "BINANCE:ANKRUSDT": "ANKRUSDT",
    "BINANCE:DGBUSDT": "DGBUSDT", "BINANCE:ILVUSDT": "ILVUSDT", "BINANCE:YGGUSDT": "YGGUSDT", "BINANCE:SKLUSDT": "SKLUSDT",
    "BINANCE:ORCAUSDT": "ORCAUSDT", "BINANCE:BABYUSDT": "BABYUSDT", "BINANCE:WOOUSDT": "WOOUSDT", "BINANCE:ERAUSDT": "ERAUSDT",
    "BINANCE:REQUSDT": "REQUSDT", "BINANCE:ICXUSDT": "ICXUSDT", "BINANCE:ZENUSDT": "ZENUSDT", "BINANCE:GMTUSDT": "GMTUSDT",
    "BINANCE:ONTUSDT": "ONTUSDT", "BINANCE:KDAUSDT": "KDAUSDT", "BINANCE:BOMEUSDT": "BOMEUSDT", "BINANCE:POLYXUSDT": "POLYXUSDT",
    "BINANCE:ENJUSDT": "ENJUSDT", "BINANCE:SSVUSDT": "SSVUSDT", "BINANCE:MASKUSDT": "MASKUSDT", "BINANCE:OSMOUSDT": "OSMOUSDT",
    "BINANCE:XNOUSDT": "XNOUSDT", "BINANCE:SXTUSDT": "SXTUSDT", "BINANCE:CYBERUSDT": "CYBERUSDT", "BINANCE:AIXBTUSDT": "AIXBTUSDT",
    "BINANCE:COTIUSDT": "COTIUSDT", "BINANCE:IOUSDT": "IOUSDT", "BINANCE:GUSDT": "GUSDT", "BINANCE:LRCUSDT": "LRCUSDT",
    "BINANCE:SXPUSDT": "SXPUSDT", "BINANCE:BANDUSDT": "BANDUSDT", "BINANCE:HOMEUSDT": "HOMEUSDT", "BINANCE:METISUSDT": "METISUSDT",
    "BINANCE:XVGUSDT": "XVGUSDT", "BINANCE:REDUSDT": "REDUSDT", "BINANCE:STORJUSDT": "STORJUSDT", "BINANCE:BICOUSDT": "BICOUSDT",
    "BINANCE:MANTAUSDT": "MANTAUSDT", "BINANCE:HIVEUSDT": "HIVEUSDT", "BINANCE:API3USDT": "API3USDT", "BINANCE:XVSUSDT": "XVSUSDT",
    "BINANCE:PIXELUSDT": "PIXELUSDT", "BINANCE:LSKUSDT": "LSKUSDT", "BINANCE:PEOPLEUSDT": "PEOPLEUSDT", "BINANCE:TRBUSDT": "TRBUSDT",
    "BINANCE:FIDAUSDT": "FIDAUSDT", "BINANCE:ANIMEUSDT": "ANIMEUSDT", "BINANCE:IOSTUSDT": "IOSTUSDT", "BINANCE:AWEUSDT": "AWEUSDT",
    "BINANCE:MEMEUSDT": "MEMEUSDT", "BINANCE:AEVOUSDT": "AEVOUSDT", "BINANCE:BANANAUSDT": "BANANAUSDT", "BINANCE:FUNUSDT": "FUNUSDT",
    "BINANCE:COOKIEUSDT": "COOKIEUSDT", "BINANCE:DIAUSDT": "DIAUSDT", "BINANCE:LQTYUSDT": "LQTYUSDT", "BINANCE:LISTAUSDT": "LISTAUSDT",
    "BINANCE:CVCUSDT": "CVCUSDT", "BINANCE:BNTUSDT": "BNTUSDT", "BINANCE:WAXPUSDT": "WAXPUSDT", "BINANCE:STRAXUSDT": "STRAXUSDT",
    "BINANCE:SIGNUSDT": "SIGNUSDT", "BINANCE:ARDRUSDT": "ARDRUSDT", "BINANCE:BBUSDT": "BBUSDT", "BINANCE:CETUSUSDT": "CETUSUSDT",
    "BINANCE:XAIUSDT": "XAIUSDT", "BINANCE:USUALUSDT": "USUALUSDT", "BINANCE:PHAUSDT": "PHAUSDT", "BINANCE:TNSRUSDT": "TNSRUSDT",
    "BINANCE:FLUXUSDT": "FLUXUSDT", "BINANCE:AUDIOUSDT": "AUDIOUSDT", "BINANCE:ARKUSDT": "ARKUSDT", "BINANCE:SPELLUSDT": "SPELLUSDT",
    "BINANCE:DENTUSDT": "DENTUSDT", "BINANCE:MAGICUSDT": "MAGICUSDT", "BINANCE:EDUUSDT": "EDUUSDT", "BINANCE:RLCUSDT": "RLCUSDT",
    "BINANCE:THEUSDT": "THEUSDT", "BINANCE:GLMRUSDT": "GLMRUSDT", "BINANCE:CHRUSDT": "CHRUSDT", "BINANCE:PUNDIXUSDT": "PUNDIXUSDT",
    "BINANCE:IQUSDT": "IQUSDT", "BINANCE:SCRUSDT": "SCRUSDT", "BINANCE:WCTUSDT": "WCTUSDT", "BINANCE:VANRYUSDT": "VANRYUSDT",
    "BINANCE:AGLDUSDT": "AGLDUSDT", "BINANCE:HUMAUSDT": "HUMAUSDT", "BINANCE:HFTUSDT": "HFTUSDT", "BINANCE:SOLVUSDT": "SOLVUSDT",
    "BINANCE:REZUSDT": "REZUSDT", "BINANCE:WINUSDT": "WINUSDT", "BINANCE:EPICUSDT": "EPICUSDT", "BINANCE:EURIUSDT": "EURIUSDT",
    "BINANCE:NILUSDT": "NILUSDT", "BINANCE:SCRTUSDT": "SCRTUSDT", "BINANCE:GNSUSDT": "GNSUSDT", "BINANCE:RAREUSDT": "RAREUSDT",
    "BINANCE:RIFUSDT": "RIFUSDT", "BINANCE:PYRUSDT": "PYRUSDT", "BINANCE:OXTUSDT": "OXTUSDT", "BINANCE:C98USDT": "C98USDT",
    "BINANCE:VELODROMEUSDT": "VELODROMEUSDT", "BINANCE:A2ZUSDT": "A2ZUSDT", "BINANCE:QKCUSDT": "QKCUSDT", "BINANCE:CTKUSDT": "CTKUSDT",
    "BINANCE:QIUSDT": "QIUSDT", "BINANCE:RESOLVUSDT": "RESOLVUSDT", "BINANCE:ASRUSDT": "ASRUSDT", "BINANCE:AIUSDT": "AIUSDT",
    "BINANCE:HMSTRUSDT": "HMSTRUSDT", "BINANCE:LUMIAUSDT": "LUMIAUSDT"
}

# 3. MAJORS: A curated list of top ~20 assets by market cap for focused analysis.
MAJORS = {
    "BINANCE:BTCUSDT": "BTCUSDT", "BINANCE:ETHUSDT": "ETHUSDT", "BINANCE:SOLUSDT": "SOLUSDT",
    "BINANCE:BNBUSDT": "BNBUSDT", "BINANCE:XRPUSDT": "XRPUSDT", "BINANCE:ADAUSDT": "ADAUSDT",
    "BINANCE:DOGEUSDT": "DOGEUSDT", "BINANCE:AVAXUSDT": "AVAXUSDT", "BINANCE:SHIBUSDT": "SHIBUSDT",
    "BINANCE:DOTUSDT": "DOTUSDT", "BINANCE:LINKUSDT": "LINKUSDT", "BINANCE:TRXUSDT": "TRXUSDT",
    "BINANCE:BCHUSDT": "BCHUSD", "BINANCE:NEARUSDT": "NEARUSDT", "BINANCE:LTCUSDT": "LTCUSDT",
    "BINANCE:UNIUSDT": "UNIUSDT", "BINANCE:ICPUSDT": "ICPUSDT", "BINANCE:ETCUSDT": "ETCUSDT",
    "BINANCE:ATOMUSDT": "ATOMUSDT", "BINANCE:TIAUSDT": "TIAUSDT",
}

# 4. MEME_COIN_BASKET: A basket of popular meme coins for tracking speculative sentiment.
MEME_COIN_BASKET = {
    "BINANCE:DOGEUSDT": "DOGEUSDT", "BINANCE:SHIBUSDT": "SHIBUSDT", "BINANCE:PEPEUSDT": "PEPEUSDT",
    "BINANCE:BONKUSDT": "BONKUSDT", "BINANCE:WIFUSDT": "WIFUSDT", "CRYPTO:FLOKIUSD": "FLOKIUSD",
    "BYBIT:SPXUSDT": "SPXUSDT", "BYBIT:PUMPUSDT": "PUMPUSDT", "CRYPTO:BUSD": "BUSD", "BYBIT:BRETTUSDT": "BRETTUSDT",
    "BYBIT:MOGUSDT": "MOGUSDT", "CRYPTO:REKTCUSD": "REKTCUSD", "CRYPTO:SNEKUSD": "SNEKUSD",
    "OKX:TURBOUSDT": "TURBOUSDT", "COINBASE:TOSHIUSD": "TOSHIUSD", "BYBIT:POPCATUSDT": "POPCATUSDT",
    "CRYPTO:FARTCOINUSD": "FARTCOINUSD"
}

# --- For data scripts: A unified dictionary of all symbols to be stored in the database ---
ALL_SYMBOLS_TO_FETCH = {**MACRO_SYMBOLS, **ALL_SYMBOLS, **MAJORS, **MEME_COIN_BASKET}