# --- Database Configuration ---
DB_FILE = "market_data.db"

# --- Symbol Categories ---

# 1. MACRO_SYMBOLS: Market-wide indicators, dominance metrics, and equities.
MACRO_SYMBOLS = {
    "CRYPTOCAP:TOTAL": "TOTAL", "CRYPTOCAP:TOTAL2": "TOTAL2", "CRYPTOCAP:TOTAL3": "TOTAL3",
    "CRYPTOCAP:OTHERS": "OTHERS", "CRYPTOCAP:USDT.D": "USDT_D", "CRYPTOCAP:USDC.D": "USDC_D",
    "CRYPTOCAP:BTC.D": "BTC_D", "NASDAQ:NDX": "NDX", "BITSTAMP:BTCUSD": "BTCUSD", "BITSTAMP:ETHUSD": "ETHUSD",
}

# 2. MAJORS_LARGE_CAP (>$1B)
MAJORS_LARGE_CAP = {
    "BINANCE:ETHUSDT": "ETHUSDT", "BINANCE:XRPUSDT": "XRPUSDT", "BINANCE:BNBUSDT": "BNBUSDT", "BINANCE:SOLUSDT": "SOLUSDT",
    "BINANCE:DOGEUSDT": "DOGEUSDT", "BINANCE:ADAUSDT": "ADAUSDT", "BINANCE:TRXUSDT": "TRXUSDT", "BINANCE:XLMUSDT": "XLMUSDT",
    "BINANCE:LINKUSDT": "LINKUSDT", "BINANCE:SUIUSDT": "SUIUSDT", "BINANCE:HBARUSDT": "HBARUSDT", "COINBASE:BCHUSD": "BCHUSD",
    "BINANCE:UNIUSDT": "UNIUSDT", "BINANCE:AVAXUSDT": "AVAXUSDT", "BINANCE:LTCUSDT": "LTCUSDT", "BINANCE:TONUSDT": "TONUSDT",
    "BINANCE:SHIBUSDT": "SHIBUSDT", "BINANCE:DOTUSDT": "DOTUSDT", "BINANCE:ONDOUSDT": "ONDOUSDT", "BINANCE:PEPEUSDT": "PEPEUSDT",
    "BINANCE:AAVEUSDT": "AAVEUSDT", "BINANCE:ENAUSDT": "ENAUSDT", "BINANCE:ARBUSDT": "ARBUSDT", "BINANCE:WLDUSDT": "WLDUSDT",
    "BINANCE:TAOUSDT": "TAOUSDT", "BINANCE:NEARUSDT": "NEARUSDT", "BINANCE:ETCUSDT": "ETCUSDT", "BINANCE:APTUSDT": "APTUSDT",
    "COINBASE:TRUMPUSD": "TRUMPUSD", "BINANCE:OPUSDT": "OPUSDT", "BINANCE:ICPUSDT": "ICPUSDT", "BINANCE:FILUSDT": "FILUSDT",
    "BINANCE:ENSUSDT": "ENSUSDT", "BINANCE:POLUSDT": "POLUSDT", "BINANCE:ALGOUSDT": "ALGOUSDT", "COINBASE:PENGUUSD": "PENGUUSD",
    "BINANCE:VETUSDT": "VETUSDT", "BINANCE:ATOMUSDT": "ATOMUSDT", "BINANCE:BONKUSDT": "BONKUSDT", "BINANCE:RAYUSDT": "RAYUSDT",
    "BINANCE:RENDERUSDT": "RENDERUSDT", "COINBASE:SEIUSD": "SEIUSD", "BINANCE:FETUSDT": "FETUSDT", "BINANCE:TIAUSDT": "TIAUSDT",
    "BINANCE:MKRUSDT": "MKRUSDT", "BINANCE:JUPUSDT": "JUPUSDT", "BINANCE:CRVUSDT": "CRVUSDT", "BINANCE:INJUSDT": "INJUSDT",
    "BINANCE:JTOUSDT": "JTOUSDT", "BINANCE:PENDLEUSDT": "PENDLEUSDT", "BINANCE:FORMUSDT": "FORMUSDT", "BINANCE:LDOUSDT": "LDOUSDT",
    "BINANCE:STXUSDT": "STXUSDT", "BINANCE:QNTUSDT": "QNTUSDT", "BINANCE:VIRTUALUSDT": "VIRTUALUSDT", "BINANCE:IMXUSDT": "IMXUSDT",
    "CRYPTO:FLOKIUSD": "FLOKIUSD", "COINBASE:GRTUSD": "GRTUSD", "BINANCE:WIFUSDT": "WIFUSDT", "BINANCE:CFXUSDT": "CFXUSDT", "BINANCE:CAKEUSDT": "CAKEUSDT",
}

# 3. MAJORS_MID_CAP (>$500M)
MAJORS_MID_CAP = {
    "BINANCE:PYTHUSDT": "PYTHUSDT", "BINANCE:KAIAUSDT": "KAIAUSDT", "BINANCE:SUSDT": "SUSDT", "BINANCE:SANDUSDT": "SANDUSDT",
    "BINANCE:XTZUSDT": "XTZUSDT", "BINANCE:JASMYUSDT": "JASMYUSDT", "BINANCE:AUSDT": "AUSDT", "BINANCE:THETAUSDT": "THETAUSDT",
    "BINANCE:NEXOUSDT": "NEXOUSDT", "BINANCE:IOTAUSDT": "IOTAUSDT", "CRYPTO:GALAUSD": "GALAUSD", "BINANCE:ETHFIUSDT": "ETHFIUSDT",
    "BINANCE:DEXEUSDT": "DEXEUSDT", "BINANCE:BTTCUSDT": "BTTCUSDT", "BINANCE:AXSUSDT": "AXSUSDT", "BINANCE:NEOUSDT": "NEOUSDT",
    "BINANCE:FLOWUSDT": "FLOWUSDT", "BINANCE:ZROUSDT": "ZROUSDT", "BINANCE:ZECUSDT": "ZECUSDT", "BINANCE:MANAUSDT": "MANAUSDT",
    "BINANCE:RUNEUSDT": "RUNEUSDT", "BINANCE:STRKUSDT": "STRKUSDT", "BINANCE:RSRUSDT": "RSRUSDT", "BINANCE:APEUSDT": "APEUSDT",
    "BINANCE:ZKUSDT": "ZKUSDT", "BINANCE:DYDXUSDT": "DYDXUSDT", "BINANCE:SYRUPUSDT": "SYRUPUSDT", "BINANCE:ARUSDT": "ARUSDT",
    "BINANCE:EIGENUSDT": "EIGENUSDT", "BINANCE:COMPUSDT": "COMPUSDT", "BINANCE:SUPERUSDT": "SUPERUSDT",
}

# 4. MAJORS_SMALL_CAP (>$100M)
MAJORS_SMALL_CAP = {
    "BINANCE:SUNUSDT": "SUNUSDT", "BINANCE:EGLDUSDT": "EGLDUSDT", "BINANCE:WUSDT": "WUSDT", "BINANCE:CVXUSDT": "CVXUSDT",
    "BINANCE:XECUSDT": "XECUSDT", "BINANCE:CHZUSDT": "CHZUSDT", "BINANCE:BEAMXUSDT": "BEAMXUSDT", "BINANCE:KAVAUSDT": "KAVAUSDT",
    "BINANCE:1INCHUSDT": "1INCHUSDT", "BINANCE:RONINUSDT": "RONINUSDT", "BINANCE:MOVEUSDT": "MOVEUSDT", "BINANCE:GNOUSDT": "GNOUSDT",
    "BINANCE:AXLUSDT": "AXLUSDT", "OKX:TURBOUSDT": "TURBOUSDT", "BINANCE:LUNCUSDT": "LUNCUSDT", "BINANCE:JSTUSDT": "JSTUSDT",
    "BINANCE:KMNOUSDT": "KMNOUSDT", "BINANCE:TWTUSDT": "TWTUSDT", "BINANCE:FTTUSDT": "FTTUSDT", "BINANCE:FXSUSDT": "FXSUSDT",
    "BINANCE:AMPUSDT": "AMPUSDT", "BINANCE:LPTUSDT": "LPTUSDT", "BINANCE:DCRUSDT": "DCRUSDT", "BINANCE:KAITOUSDT": "KAITOUSDT",
    "BINANCE:DASHUSDT": "DASHUSDT", "BINANCE:IOTXUSDT": "IOTXUSDT", "BINANCE:OMUSDT": "OMUSDT", "BINANCE:KSMUSDT": "KSMUSDT",
    "BINANCE:PROVEUSDT": "PROVEUSDT", "BINANCE:ROSEUSDT": "ROSEUSDT", "BINANCE:ARKMUSDT": "ARKMUSDT", "BINANCE:CKBUSDT": "CKBUSDT",
    "BINANCE:TFUELUSDT": "TFUELUSDT", "BINANCE:GLMUSDT": "GLMUSDT", "BINANCE:BERAUSDT": "BERAUSDT", "BINANCE:PNUTUSDT": "PNUTUSDT",
    "BINANCE:MINAUSDT": "MINAUSDT", "BINANCE:SFPUSDT": "SFPUSDT", "BINANCE:SUSHIUSDT": "SUSHIUSDT", "BINANCE:ZILUSDT": "ZILUSDT",
    "BINANCE:SNXUSDT": "SNXUSDT", "BINANCE:BATUSDT": "BATUSDT", "BINANCE:MEUSDT": "MEUSDT", "BINANCE:CELOUSDT": "CELOUSDT",
    "BINANCE:QTUMUSDT": "QTUMUSDT", "BINANCE:ZRXUSDT": "ZRXUSDT", "BINANCE:RVNUSDT": "RVNUSDT", "BINANCE:ASTRUSDT": "ASTRUSDT",
    "BINANCE:ACHUSDT": "ACHUSDT", "BINANCE:BLURUSDT": "BLURUSDT", "BINANCE:GASUSDT": "GASUSDT", "BINANCE:ORDIUSDT": "ORDIUSDT",
    "BINANCE:BIOUSDT": "BIOUSDT", "BINANCE:SAGAUSDT": "SAGAUSDT", "BINANCE:SAHARAUSDT": "SAHARAUSDT", "BINANCE:NOTUSDT": "NOTUSDT",
    "BINANCE:COWUSDT": "COWUSDT", "BINANCE:YFIUSDT": "YFIUSDT", "BINANCE:DYMUSDT": "DYMUSDT", "BINANCE:LUNAUSDT": "LUNAUSDT",
    "BINANCE:IDUSDT": "IDUSDT", "BINANCE:ALTUSDT": "ALTUSDT", "BINANCE:VANAUSDT": "VANAUSDT", "BINANCE:BIGTIMEUSDT": "BIGTIMEUSDT",
    "BINANCE:NEIROUSDT": "NEIROUSDT", "BINANCE:STGUSDT": "STGUSDT", "BINANCE:VTHOUSDT": "VTHOUSDT", "BINANCE:RPLUSDT": "RPLUSDT",
    "BINANCE:HOTUSDT": "HOTUSDT", "BINANCE:SKLUSDT": "SKLUSDT", "BINANCE:LAYERUSDT": "LAYERUSDT", "BINANCE:NXPCUSDT": "NXPCUSDT",
    "BINANCE:ACXUSDT": "ACXUSDT", "BINANCE:SCUSDT": "SCUSDT", "BINANCE:POWRUSDT": "POWRUSDT", "BINANCE:TUSDT": "TUSDT",
    "BINANCE:ONEUSDT": "ONEUSDT", "BINANCE:GMXUSDT": "GMXUSDT", "BINANCE:PROMUSDT": "PROMUSDT", "BINANCE:SPKUSDT": "SPKUSDT",
    "BINANCE:DGBUSDT": "DGBUSDT", "BINANCE:ANKRUSDT": "ANKRUSDT", "BINANCE:OMNIUSDT": "OMNIUSDT", "BINANCE:UMAUSDT": "UMAUSDT",
    "BINANCE:YGGUSDT": "YGGUSDT", "BINANCE:BABYUSDT": "BABYUSDT", "BINANCE:ILVUSDT": "ILVUSDT", "BINANCE:WOOUSDT": "WOOUSDT",
    "BINANCE:ORCAUSDT": "ORCAUSDT", "BINANCE:KDAUSDT": "KDAUSDT", "BINANCE:ICXUSDT": "ICXUSDT", "BINANCE:REQUSDT": "REQUSDT",
    "BINANCE:ZENUSDT": "ZENUSDT", "BINANCE:ONTUSDT": "ONTUSDT", "BINANCE:GMTUSDT": "GMTUSDT", "BINANCE:ERAUSDT": "ERAUSDT",
    "BINANCE:BOMEUSDT": "BOMEUSDT", "BINANCE:ENJUSDT": "ENJUSDT", "BINANCE:POLYXUSDT": "POLYXUSDT", "BINANCE:OSMOUSDT": "OSMOUSDT",
    "BINANCE:SSVUSDT": "SSVUSDT", "BINANCE:MASKUSDT": "MASKUSDT", "BINANCE:COTIUSDT": "COTIUSDT", "BINANCE:XNOUSDT": "XNOUSDT",
    "BINANCE:SXTUSDT": "SXTUSDT", "BINANCE:LRCUSDT": "LRCUSDT", "BINANCE:AIXBTUSDT": "AIXBTUSDT", "BINANCE:IOUSDT": "IOUSDT",
    "BINANCE:GUSDT": "GUSDT", "BINANCE:CYBERUSDT": "CYBERUSDT", "BINANCE:HOMEUSDT": "HOMEUSDT", "BINANCE:SXPUSDT": "SXPUSDT",
    "BINANCE:BANDUSDT": "BANDUSDT", "BINANCE:METISUSDT": "METISUSDT", "BINANCE:XVGUSDT": "XVGUSDT", "BINANCE:MANTAUSDT": "MANTAUSDT",
    "BINANCE:REDUSDT": "REDUSDT", "BINANCE:STORJUSDT": "STORJUSDT", "BINANCE:BICOUSDT": "BICOUSDT", "BINANCE:PIXELUSDT": "PIXELUSDT",
    "BINANCE:MEMEUSDT": "MEMEUSDT", "BINANCE:API3USDT": "API3USDT", "BINANCE:HIVEUSDT": "HIVEUSDT", "BINANCE:PEOPLEUSDT": "PEOPLEUSDT",
    "BINANCE:FIDAUSDT": "FIDAUSDT", "BINANCE:TRBUSDT": "TRBUSDT", "BINANCE:XVSUSDT": "XVSUSDT", "BINANCE:AEVOUSDT": "AEVOUSDT",
    "BINANCE:ANIMEUSDT": "ANIMEUSDT", "BINANCE:BANANAUSDT": "BANANAUSDT", "BINANCE:LSKUSDT": "LSKUSDT", "BINANCE:IOSTUSDT": "IOSTUSDT",
    "BINANCE:COOKIEUSDT": "COOKIEUSDT", "BINANCE:AWEUSDT": "AWEUSDT", "BINANCE:CETUSUSDT": "CETUSUSDT", "BINANCE:SIGNUSDT": "SIGNUSDT",
    "BINANCE:CVCUSDT": "CVCUSDT", "BINANCE:LQTYUSDT": "LQTYUSDT", "BINANCE:FUNUSDT": "FUNUSDT", "BINANCE:DIAUSDT": "DIAUSDT",
    "BINANCE:BBUSDT": "BBUSDT", "BINANCE:LISTAUSDT": "LISTAUSDT",
}

# 5. MAJORS_MICRO_CAP (>$50M)
MAJORS_MICRO_CAP = {
    "BINANCE:WAXPUSDT": "WAXPUSDT", "BINANCE:STRAXUSDT": "STRAXUSDT", "BINANCE:BNTUSDT": "BNTUSDT", "BINANCE:USUALUSDT": "USUALUSDT",
    "BINANCE:XAIUSDT": "XAIUSDT", "BINANCE:ARDRUSDT": "ARDRUSDT", "BINANCE:PHAUSDT": "PHAUSDT", "BINANCE:TNSRUSDT": "TNSRUSDT",
    "BINANCE:FLUXUSDT": "FLUXUSDT", "BINANCE:SCRUSDT": "SCRUSDT", "BINANCE:ARKUSDT": "ARKUSDT", "BINANCE:CGPTUSDT": "CGPTUSDT",
    "BINANCE:AUDIOUSDT": "AUDIOUSDT", "BINANCE:SPELLUSDT": "SPELLUSDT", "BINANCE:DENTUSDT": "DENTUSDT", "BINANCE:CHRUSDT": "CHRUSDT",
    "BINANCE:THEUSDT": "THEUSDT", "BINANCE:EDUUSDT": "EDUUSDT", "BINANCE:RLCUSDT": "RLCUSDT", "BINANCE:PUNDIXUSDT": "PUNDIXUSDT",
    "BINANCE:TKOUSDT": "TKOUSDT", "BINANCE:MAGICUSDT": "MAGICUSDT", "BINANCE:IQUSDT": "IQUSDT", "BINANCE:GLMRUSDT": "GLMRUSDT",
    "BINANCE:NTRNUSDT": "NTRNUSDT", "BINANCE:OGUSDT": "OGUSDT", "BINANCE:DOGSUSDT": "DOGSUSDT", "BINANCE:SOPHUSDT": "SOPHUSDT",
    "BINANCE:KNCUSDT": "KNCUSDT", "BINANCE:JOEUSDT": "JOEUSDT", "BINANCE:1000CATUSDT": "1000CATUSDT", "BINANCE:AUCTIONUSDT": "AUCTIONUSDT",
    "BINANCE:ONGUSDT": "ONGUSDT", "BINANCE:CELRUSDT": "CELRUSDT", "BINANCE:NEWTUSDT": "NEWTUSDT", "BINANCE:OGNUSDT": "OGNUSDT",
    "BINANCE:INITUSDT": "INITUSDT", "BINANCE:LAUSDT": "LAUSDT", "BINANCE:PONDUSDT": "PONDUSDT", "BINANCE:STEEMUSDT": "STEEMUSDT",
    "BINANCE:SLPUSDT": "SLPUSDT", "BINANCE:NMRUSDT": "NMRUSDT", "BINANCE:MOVRUSDT": "MOVRUSDT", "BINANCE:VANRYUSDT": "VANRYUSDT",
    "BINANCE:TOWNSUSDT": "TOWNSUSDT", "BINANCE:CTSIUSDT": "CTSIUSDT", "BINANCE:MTLUSDT": "MTLUSDT", "BINANCE:RADUSDT": "RADUSDT",
    "BINANCE:HYPERUSDT": "HYPERUSDT", "BINANCE:SANTOSUSDT": "SANTOSUSDT", "BINANCE:AGLDUSDT": "AGLDUSDT", "BINANCE:TREEUSDT": "TREEUSDT",
    "BINANCE:WCTUSDT": "WCTUSDT", "BINANCE:HFTUSDT": "HFTUSDT", "BINANCE:EPICUSDT": "EPICUSDT", "BINANCE:NILUSDT": "NILUSDT",
    "BINANCE:WINUSDT": "WINUSDT", "BINANCE:REZUSDT": "REZUSDT", "BINANCE:HUMAUSDT": "HUMAUSDT", "BINANCE:GNSUSDT": "GNSUSDT",
    "BINANCE:SOLVUSDT": "SOLVUSDT", "BINANCE:SCRTUSDT": "SCRTUSDT", "BINANCE:EURIUSDT": "EURIUSDT", "BINANCE:RAREUSDT": "RAREUSDT",
    "BINANCE:RIFUSDT": "RIFUSDT", "BINANCE:C98USDT": "C98USDT", "BINANCE:OXTUSDT": "OXTUSDT", "BINANCE:PYRUSDT": "PYRUSDT",
    "BINANCE:VELODROMEUSDT": "VELODROMEUSDT", "BINANCE:CTKUSDT": "CTKUSDT", "BINANCE:QIUSDT": "QIUSDT", "BINANCE:QKCUSDT": "QKCUSDT",
    "BINANCE:ASRUSDT": "ASRUSDT", "BINANCE:RESOLVUSDT": "RESOLVUSDT", "BINANCE:ALPINEUSDT": "ALPINEUSDT", "BINANCE:AIUSDT": "AIUSDT",
    "BINANCE:HMSTRUSDT": "HMSTRUSDT", "BINANCE:LUMIAUSDT": "LUMIAUSDT", "BINANCE:TUTUSDT": "TUTUSDT", "BINANCE:ARPAUSDT": "ARPAUSDT",
    "BINANCE:DODOUSDT": "DODOUSDT",
}

# 6. MEME_COIN_BASKET
MEME_COIN_BASKET = {
    "BINANCE:DOGEUSDT": "DOGEUSDT", "BINANCE:SHIBUSDT": "SHIBUSDT", "BINANCE:PEPEUSDT": "PEPEUSDT",
    "BINANCE:BONKUSDT": "BONKUSDT", "BINANCE:WIFUSDT": "WIFUSDT", "CRYPTO:FLOKIUSD": "FLOKIUSD",
    "BYBIT:SPXUSDT": "SPXUSDT", "BYBIT:PUMPUSDT": "PUMPUSDT", "CRYPTO:BUSD": "BUSD", "BYBIT:BRETTUSDT": "BRETTUSDT",
    "BYBIT:MOGUSDT": "MOGUSDT", "CRYPTO:REKTCUSD": "REKTCUSD", "CRYPTO:SNEKUSD": "SNEKUSD",
    "OKX:TURBOUSDT": "TURBOUSDT", "COINBASE:TOSHIUSD": "TOSHIUSD", "BYBIT:POPCATUSDT": "POPCATUSDT",
    "CRYPTO:FARTCOINUSD": "FARTCOINUSD"
}


# --- Combined list for data fetching ---
# This ensures all unique assets from all baskets are fetched.
ALL_SYMBOLS_TO_FETCH = {
    **MACRO_SYMBOLS,
    **MAJORS_LARGE_CAP,
    **MAJORS_MID_CAP,
    **MAJORS_SMALL_CAP,
    **MAJORS_MICRO_CAP,
    **MEME_COIN_BASKET
}
